# Generated by Django 3.1.2 on 2021-01-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0002_problemtemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ident',
            field=models.CharField(max_length=10, null=True, verbose_name='Код площадки'),
        ),
        migrations.AddField(
            model_name='place',
            name='uid',
            field=models.CharField(max_length=12, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='place',
            name='addr',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
    ]
