# Generated by Django 3.1.2 on 2021-01-26 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0003_auto_20210116_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=20, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Размещения'},
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_closed',
            field=models.DateTimeField(null=True, verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_created',
            field=models.DateTimeField(null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='problemtemp',
            name='num',
            field=models.CharField(max_length=10, verbose_name='Временная'),
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='man.place', verbose_name='Размещение')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, verbose_name='Время добавления')),
                ('text', models.TextField(max_length=255, verbose_name='Содержание')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='man.problem', verbose_name='К проблеме')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='responsible',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='man.companies', verbose_name='Текущий исполнитель'),
        ),
    ]
