# Generated by Django 3.1.2 on 2021-01-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0006_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='num',
            field=models.CharField(max_length=10, unique=True, verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
    ]
