# Generated by Django 3.1.2 on 2021-01-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0007_auto_20210127_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='ident',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True, verbose_name='Код площадки'),
        ),
        migrations.AlterField(
            model_name='place',
            name='uid',
            field=models.CharField(blank=True, default=' ', max_length=12, null=True, verbose_name='Идентификатор'),
        ),
    ]
